package poly.common;

public enum PageType {
	USER_MANAGEMENT_PAGE, VIDEOS_MANAGEMENT_PAGE, LISTALL_MANAGEMENT_PAGE, 
	SITE_VIDEOS_PAGE,SITE_VIDEO_INFO_PAGE, SITE_VIDEO_LIKE_PAGE,SITE_CHANGE_PASS_PAGE,
	SITE_REGISTER_PAGE, SITE_LOGIN_PAGE,
	SITE_REPORT_PAGE,
	SITE_SEND_MAIL_PAGE
}
